---
# 1. Установка nginx (пакет)
# 2. Проверить, что он запущен
# 3. Указать путь до нашего файла с htlm
- name: install nginx
  hosts: [ nginx ]
  become: True
  vars:
    nginx_conf_name: "superwebappssss.conf"
    nginx_conf_path: "/etc/nginx/sites-enabled"
    service_domain: "www.xxx.yyy"
    nginx_port: 80
    site_path: "/var/www/html"
    domains:
      - "www.xxx.yyy"
      - "sdfsdfds.xgfgd"
      - "dsfdsfds.xxx"
  tasks:
    - name: install nginx package
      apt:
        name:
          - nginx
        update_cache: True
    - name: print domain
      shell:
        cmd: "cat {{ service_domain }}"
 
    - name: set nginx conf
      template:
        src: nginx.conf.j2
        dest: "{{ nginx_conf_path }}/{{ nginx_conf_name }}"
      notify: restart nginx

    - name: start nginx
      shell:
        cmd: "systemctl start nginx"

  handlers:
    - name: restart nginx
      service:
        service: nginx
        state: restarted

